@SwipeHire.Api_HostAddress = http://localhost:5000
@StudentUid = replace_with_student_firebase_uid
@CompanyUid = replace_with_company_firebase_uid
@JobId = replace_with_job_document_id

GET {{SwipeHire.Api_HostAddress}}/api/jobs
Accept: application/json

###

GET {{SwipeHire.Api_HostAddress}}/api/students
Accept: application/json

###

POST {{SwipeHire.Api_HostAddress}}/api/location/geocode
Content-Type: application/json

{
  "address": "123 Rivonia Road, Sandton"
}

###

POST {{SwipeHire.Api_HostAddress}}/api/swipes
Content-Type: application/json

{
  "userId": "{{StudentUid}}",
  "targetId": "{{JobId}}",
  "targetUserId": "{{CompanyUid}}",
  "isLike": true
}

###

GET {{SwipeHire.Api_HostAddress}}/api/users/{{StudentUid}}/saved
Accept: application/json

###

PUT {{SwipeHire.Api_HostAddress}}/api/users/{{StudentUid}}/saved/job/{{JobId}}
Content-Type: application/json

{
  "saved": true
}

###

PUT {{SwipeHire.Api_HostAddress}}/api/users/{{StudentUid}}/settings
Content-Type: application/json

{
  "pushNotifications": true,
  "matchAlerts": true,
  "messageAlerts": true,
  "profileVisible": true
}