package com.swipehire.app.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.staticCompositionLocalOf
import com.swipehire.app.data.AppLanguage

val LocalAppLanguage = staticCompositionLocalOf { AppLanguage.ENGLISH }

@Composable
fun tr(english: String): String = when (LocalAppLanguage.current) {
    AppLanguage.ENGLISH -> english
    AppLanguage.ISIZULU -> isiZulu[english] ?: english
    AppLanguage.AFRIKAANS -> afrikaans[english] ?: english
    AppLanguage.SESOTHO -> sesotho[english] ?: english
}

private val isiZulu = mapOf(
    "Discover" to "Thola",
    "Matches" to "Ukuhambisana",
    "Alerts" to "Izaziso",
    "Profile" to "Iphrofayela",
    "Settings" to "Izilungiselelo",
    "Continue with Google" to "Qhubeka nge-Google",
    "or email" to "noma i-imeyili",
    "Email" to "I-imeyili",
    "Password" to "Iphasiwedi",
    "Confirm password" to "Qinisekisa iphasiwedi",
    "Sign in" to "Ngena",
    "Create account" to "Dala i-akhawunti",
    "Create an account" to "Dala i-akhawunti",
    "Already registered?" to "Usuvele ubhalisile?",
    "Forgot password?" to "Ukhohlwe iphasiwedi?",
    "Use biometric sign-in" to "Ngena nge-biometric",
    "Find your\nnext role" to "Thola umsebenzi\nwakho olandelayo",
    "Find your\nnext hire" to "Thola umsebenzi\nowufunayo",
    "Swipe right to apply, left to pass." to "Swayipha kwesokudla ukufaka isicelo, kwesobunxele ukudlula.",
    "Swipe right to shortlist, left to pass." to "Swayipha kwesokudla ukukhetha, kwesobunxele ukudlula.",
    "Near you" to "Eduze kwakho",
    "Search role, company, or skill" to "Sesha umsebenzi, inkampani noma ikhono",
    "All" to "Konke",
    "Undo" to "Hlehlisa",
    "View location" to "Buka indawo",
    "You're all caught up" to "Usuqedile konke",
    "Check back soon for new matches." to "Buya maduze ukuze ubone okusha.",
    "No matches for that search" to "Akukho okufanayo kulokho kusesha",
    "Try a different keyword or clear filters." to "Zama elinye igama noma susa izihlungi.",
    "Skills" to "Amakhono",
    "Requirements" to "Izidingo",
    "It's a Match!" to "Kuyahambisana!",
    "Send a message" to "Thumela umlayezo",
    "Keep swiping" to "Qhubeka uswayipha",
    "No matches yet — keep swiping!" to "Akukho ukuhambisana okwamanje — qhubeka uswayipha!",
    "Chat unavailable" to "Ingxoxo ayitholakali",
    "Messaging becomes available only after both accounts like each other." to "Imiyalezo ivuleka kuphela uma ama-akhawunti womabili ethanda omunye nomunye.",
    "Message..." to "Umlayezo...",
    "View CV" to "Buka i-CV",
    "Sending" to "Iyathumela",
    "Sent" to "Ithunyelwe",
    "Read" to "Ifundiwe",
    "Matches and messages that need your attention." to "Ukuhambisana nemiyalezo edinga ukunakwa kwakho.",
    "Alerts are switched off in Settings." to "Izaziso zivaliwe kuzilungiselelo.",
    "You have no new alerts." to "Awunazo izaziso ezintsha.",
    "Profile strength" to "Amandla ephrofayela",
    "About" to "Mayelana",
    "Portfolio" to "Iphothifoliyo",
    "Upload CV (PDF)" to "Layisha i-CV (PDF)",
    "Open uploaded CV" to "Vula i-CV elayishiwe",
    "Milestone badges" to "Amabheji empumelelo",
    "First Match" to "Ukuhambisana kokuqala",
    "5 Companies Interested" to "Izinkampani ezi-5 zinentshisekelo",
    "Profile Complete" to "Iphrofayela iphelele",
    "Complete your profile and make connections to earn badges." to "Qedela iphrofayela futhi uxhumane ukuze uthole amabheji.",
    "Application activity" to "Umsebenzi wezicelo",
    "Average reply time" to "Isikhathi esimaphakathi sokuphendula",
    "No replies yet" to "Azikho izimpendulo okwamanje",
    "Edit" to "Hlela",
    "Edit profile" to "Hlela iphrofayela",
    "Save" to "Londoloza",
    "Cancel" to "Khansela",
    "Log out / switch account" to "Phuma / shintsha i-akhawunti",
    "Your job listings" to "Izikhangiso zakho zemisebenzi",
    "Create a job posting" to "Dala isikhangiso somsebenzi",
    "Delete listing" to "Susa isikhangiso",
    "You have not published a job yet." to "Awukakashicileli umsebenzi.",
    "Notifications" to "Izaziso",
    "Push notifications" to "Izaziso zohlelo",
    "New match alerts" to "Izaziso zokuhambisana okusha",
    "Message alerts" to "Izaziso zemiyalezo",
    "Privacy" to "Ubumfihlo",
    "Profile visibility" to "Ukubonakala kwephrofayela",
    "Appearance" to "Ukubukeka",
    "Security" to "Ukuphepha",
    "Biometric lock" to "Ilokhi ye-biometric",
    "Language" to "Ulimi",
    "Light" to "Khanya",
    "Dark" to "Mnyama",
    "Match system" to "Landela uhlelo",
    "Log out" to "Phuma",
    "Jobs near you" to "Imisebenzi eduze kwakho",
    "Allow location access" to "Vumela ukufinyelela endaweni",
    "See jobs close to you" to "Bona imisebenzi eseduze kwakho",
    "Get directions" to "Thola izikhombisi-ndlela",
    "Loading job location…" to "Kulayishwa indawo yomsebenzi…",
    "Create job" to "Dala umsebenzi",
    "Job title" to "Isihloko somsebenzi",
    "Company" to "Inkampani",
    "Work address" to "Ikheli lomsebenzi",
    "Work arrangement" to "Uhlobo lomsebenzi",
    "Required skills" to "Amakhono adingekayo",
    "Salary range" to "Ibanga lomholo",
    "Description" to "Incazelo",
    "Geocode and publish" to "Thola indawo bese ushicilela",
    "Who's\nswiping today?" to "Ubani\noswayiphayo namuhla?",
    "I'm a Student" to "Ngingumfundi",
    "I'm Hiring" to "Ngiyaqasha",
    "Discover roles from companies that swipe on you" to "Thola imisebenzi ezinkampanini ezikukhethayo",
    "Swipe through student profiles to find your next grad" to "Swayipha amaphrofayela abafundi ukuze uthole ozomqasha",
    "Sign in to browse SwipeHire." to "Ngena ukuze usebenzise i-SwipeHire.",
    "Publish a role with a verified map location" to "Shicilela umsebenzi onendawo eqinisekisiwe",
    "MATCH" to "FANA",
    "PASS" to "DLULA",
    "Saved" to "Okulondoloziwe", "reviewed" to "okubuyekeziwe", "Browsing as" to "Usebenzisa njengo",
    "Student" to "Umfundi", "Log out to use a different account or role" to "Phuma ukuze usebenzise enye i-akhawunti noma indima",
    "New match" to "Ukuhambisana okusha", "New message from" to "Umlayezo omusha ovela ku", "You matched with" to "Uhambisane no"
)

private val afrikaans = mapOf(
    "Discover" to "Ontdek", "Matches" to "Pasvorms", "Alerts" to "Waarskuwings",
    "Profile" to "Profiel", "Settings" to "Instellings", "Continue with Google" to "Gaan voort met Google",
    "or email" to "of e-pos", "Email" to "E-pos", "Password" to "Wagwoord",
    "Confirm password" to "Bevestig wagwoord", "Sign in" to "Meld aan", "Create account" to "Skep rekening",
    "Create an account" to "Skep 'n rekening", "Already registered?" to "Reeds geregistreer?",
    "Forgot password?" to "Wagwoord vergeet?", "Use biometric sign-in" to "Gebruik biometriese aanmelding",
    "Find your\nnext role" to "Vind jou\nvolgende rol", "Find your\nnext hire" to "Vind jou\nvolgende aanstelling",
    "Swipe right to apply, left to pass." to "Swiep regs om aansoek te doen, links om oor te slaan.",
    "Swipe right to shortlist, left to pass." to "Swiep regs om te kortlys, links om oor te slaan.",
    "Near you" to "Naby jou", "Search role, company, or skill" to "Soek rol, maatskappy of vaardigheid",
    "All" to "Alles", "Undo" to "Ontdoen", "View location" to "Bekyk ligging",
    "You're all caught up" to "Jy is heeltemal op datum", "Check back soon for new matches." to "Kyk binnekort weer vir nuwe pasvorms.",
    "No matches for that search" to "Geen resultate vir daardie soektog nie", "Try a different keyword or clear filters." to "Probeer 'n ander sleutelwoord of verwyder filters.",
    "Skills" to "Vaardighede", "Requirements" to "Vereistes", "It's a Match!" to "Dit is 'n pasvorm!",
    "Send a message" to "Stuur 'n boodskap", "Keep swiping" to "Hou aan swiep",
    "No matches yet — keep swiping!" to "Nog geen pasvorms nie — hou aan swiep!", "Chat unavailable" to "Klets nie beskikbaar nie",
    "Messaging becomes available only after both accounts like each other." to "Boodskappe is eers beskikbaar wanneer albei rekeninge van mekaar hou.",
    "Message..." to "Boodskap...", "View CV" to "Bekyk CV", "Sending" to "Stuur tans", "Sent" to "Gestuur", "Read" to "Gelees",
    "Matches and messages that need your attention." to "Pasvorms en boodskappe wat jou aandag nodig het.",
    "Alerts are switched off in Settings." to "Waarskuwings is in Instellings afgeskakel.", "You have no new alerts." to "Jy het geen nuwe waarskuwings nie.",
    "Profile strength" to "Profielsterkte", "About" to "Oor", "Portfolio" to "Portefeulje",
    "Upload CV (PDF)" to "Laai CV op (PDF)", "Open uploaded CV" to "Open opgelaaide CV", "Milestone badges" to "Mylpaalkentekens",
    "First Match" to "Eerste pasvorm", "5 Companies Interested" to "5 maatskappye stel belang", "Profile Complete" to "Profiel voltooi",
    "Complete your profile and make connections to earn badges." to "Voltooi jou profiel en maak verbindings om kentekens te verdien.",
    "Application activity" to "Aansoekaktiwiteit", "Average reply time" to "Gemiddelde antwoordtyd", "No replies yet" to "Nog geen antwoorde nie",
    "Edit" to "Wysig", "Edit profile" to "Wysig profiel", "Save" to "Stoor", "Cancel" to "Kanselleer",
    "Log out / switch account" to "Meld af / verander rekening", "Your job listings" to "Jou poslyste",
    "Create a job posting" to "Skep 'n posplasing", "Delete listing" to "Verwyder lys", "You have not published a job yet." to "Jy het nog geen pos gepubliseer nie.",
    "Notifications" to "Kennisgewings", "Push notifications" to "Stootkennisgewings", "New match alerts" to "Nuwe pasvormwaarskuwings",
    "Message alerts" to "Boodskapwaarskuwings", "Privacy" to "Privaatheid", "Profile visibility" to "Profielsigbaarheid",
    "Appearance" to "Voorkoms", "Security" to "Sekuriteit", "Biometric lock" to "Biometriese slot", "Language" to "Taal",
    "Light" to "Lig", "Dark" to "Donker", "Match system" to "Volg stelsel", "Log out" to "Meld af",
    "Jobs near you" to "Werk naby jou", "Allow location access" to "Laat liggingtoegang toe", "See jobs close to you" to "Sien werk naby jou",
    "Get directions" to "Kry aanwysings", "Loading job location…" to "Laai werksligging…", "Create job" to "Skep pos",
    "Job title" to "Postitel", "Company" to "Maatskappy", "Work address" to "Werkadres", "Work arrangement" to "Werkreëling",
    "Required skills" to "Vereiste vaardighede", "Salary range" to "Salarisreeks", "Description" to "Beskrywing",
    "Geocode and publish" to "Vind ligging en publiseer",
    "Who's\nswiping today?" to "Wie\nswiep vandag?",
    "I'm a Student" to "Ek is 'n student",
    "I'm Hiring" to "Ek stel aan",
    "Discover roles from companies that swipe on you" to "Ontdek rolle van maatskappye wat jou kies",
    "Swipe through student profiles to find your next grad" to "Swiep deur studenteprofiele om jou volgende gegradueerde te vind",
    "Sign in to browse SwipeHire." to "Meld aan om SwipeHire te gebruik.",
    "Publish a role with a verified map location" to "Publiseer 'n rol met 'n bevestigde kaartligging",
    "MATCH" to "PAS",
    "PASS" to "SLAAN OOR",
    "Saved" to "Gestoor", "reviewed" to "hersien", "Browsing as" to "Gebruik as",
    "Student" to "Student", "Log out to use a different account or role" to "Meld af om 'n ander rekening of rol te gebruik",
    "New match" to "Nuwe pasvorm", "New message from" to "Nuwe boodskap van", "You matched with" to "Jy pas by"
)

private val sesotho = mapOf(
    "Discover" to "Fumana", "Matches" to "Tse tsamaellanang", "Alerts" to "Ditemoso",
    "Profile" to "Profaele", "Settings" to "Litlhophiso", "Continue with Google" to "Tswela pele ka Google",
    "or email" to "kapa imeile", "Email" to "Imeile", "Password" to "Phasewete",
    "Confirm password" to "Netefatsa phasewete", "Sign in" to "Kena", "Create account" to "Theha akhaonto",
    "Create an account" to "Theha akhaonto", "Already registered?" to "O se o ngodisitse?",
    "Forgot password?" to "O lebetse phasewete?", "Use biometric sign-in" to "Kena ka biometric",
    "Find your\nnext role" to "Fumana mosebetsi\no latelang", "Find your\nnext hire" to "Fumana mohiruwa\no latelang",
    "Swipe right to apply, left to pass." to "Swaepa ka ho le letona ho etsa kopo, ka ho le letshehadi ho feta.",
    "Swipe right to shortlist, left to pass." to "Swaepa ka ho le letona ho kgetha, ka ho le letshehadi ho feta.",
    "Near you" to "Haufi le wena", "Search role, company, or skill" to "Batla mosebetsi, khamphani kapa bokgoni",
    "All" to "Tsohle", "Undo" to "Etsolla", "View location" to "Sheba sebaka",
    "You're all caught up" to "O qetile tsohle", "Check back soon for new matches." to "Kgutla haufinyane bakeng sa tse ntjha.",
    "No matches for that search" to "Ha ho sephetho sa patlo eo", "Try a different keyword or clear filters." to "Leka lentswe le leng kapa hlakola difilthara.",
    "Skills" to "Bokgoni", "Requirements" to "Ditlhoko", "It's a Match!" to "Le a tsamaellana!",
    "Send a message" to "Romela molaetsa", "Keep swiping" to "Tswela pele ho swaepa",
    "No matches yet — keep swiping!" to "Ha ho tse tsamaellanang — tswela pele ho swaepa!", "Chat unavailable" to "Puisano ha e fumanehe",
    "Messaging becomes available only after both accounts like each other." to "Melaetsa e fumaneha feela ha diakhaonto ka bobedi di ratana.",
    "Message..." to "Molaetsa...", "View CV" to "Sheba CV", "Sending" to "E a romelwa", "Sent" to "E rometswe", "Read" to "E badilwe",
    "Matches and messages that need your attention." to "Tse tsamaellanang le melaetsa e hlokang tlhokomelo ya hao.",
    "Alerts are switched off in Settings." to "Ditemoso di timilwe ho Litlhophiso.", "You have no new alerts." to "Ha o na ditemoso tse ntjha.",
    "Profile strength" to "Matla a profaele", "About" to "Ka nna", "Portfolio" to "Potefolio",
    "Upload CV (PDF)" to "Kenya CV (PDF)", "Open uploaded CV" to "Bula CV e kentsweng", "Milestone badges" to "Dibeche tsa katleho",
    "First Match" to "Tsamaisano ya pele", "5 Companies Interested" to "Dikhamphani tse 5 di na le thahasello", "Profile Complete" to "Profaele e phethehile",
    "Complete your profile and make connections to earn badges." to "Phethela profaele mme o etse dikgokahano ho fumana dibeche.",
    "Application activity" to "Tshebetso ya dikopo", "Average reply time" to "Nako e tlwaelehileng ya karabo", "No replies yet" to "Ha ho dikarabo",
    "Edit" to "Fetola", "Edit profile" to "Fetola profaele", "Save" to "Boloka", "Cancel" to "Hlakola",
    "Log out / switch account" to "Tswa / fetola akhaonto", "Your job listings" to "Manane a hao a mesebetsi",
    "Create a job posting" to "Theha papatso ya mosebetsi", "Delete listing" to "Hlakola lenane", "You have not published a job yet." to "Ha o eso phatlalatse mosebetsi.",
    "Notifications" to "Ditsebiso", "Push notifications" to "Ditsebiso tsa sesebediswa", "New match alerts" to "Ditemoso tsa tsamaisano e ntjha",
    "Message alerts" to "Ditemoso tsa melaetsa", "Privacy" to "Lekunutu", "Profile visibility" to "Ponahalo ya profaele",
    "Appearance" to "Ponahalo", "Security" to "Tshireletso", "Biometric lock" to "Senotlolo sa biometric", "Language" to "Puo",
    "Light" to "Lesedi", "Dark" to "Lefifi", "Match system" to "Latela sistimi", "Log out" to "Tswa",
    "Jobs near you" to "Mesebetsi e haufi le wena", "Allow location access" to "Dumella sebaka", "See jobs close to you" to "Bona mesebetsi e haufi",
    "Get directions" to "Fumana ditsela", "Loading job location…" to "Sebaka sa mosebetsi se a laelwa…", "Create job" to "Theha mosebetsi",
    "Job title" to "Sehlooho sa mosebetsi", "Company" to "Khamphani", "Work address" to "Aterese ya mosebetsi", "Work arrangement" to "Mokgwa wa mosebetsi",
    "Required skills" to "Bokgoni bo hlokahalang", "Salary range" to "Boemo ba moputso", "Description" to "Tlhaloso",
    "Geocode and publish" to "Fumana sebaka mme o phatlalatse",
    "Who's\nswiping today?" to "Ke mang\nya swaepang kajeno?",
    "I'm a Student" to "Ke moithuti",
    "I'm Hiring" to "Ke a hira",
    "Discover roles from companies that swipe on you" to "Fumana mesebetsi dikhamphaning tse o kgethang",
    "Swipe through student profiles to find your next grad" to "Swaepa diprofaele tsa baithuti ho fumana mohiruwa",
    "Sign in to browse SwipeHire." to "Kena ho sebedisa SwipeHire.",
    "Publish a role with a verified map location" to "Phatlalatsa mosebetsi o nang le sebaka se netefaditsweng",
    "MATCH" to "TSAMAELLANA",
    "PASS" to "FETA",
    "Saved" to "Tse bolokilweng", "reviewed" to "tse hlahlojwang", "Browsing as" to "O sebedisa jwalo ka",
    "Student" to "Moithuti", "Log out to use a different account or role" to "Tswa ho sebedisa akhaonto kapa karolo e nngwe",
    "New match" to "Tsamaisano e ntjha", "New message from" to "Molaetsa o motjha o tswang ho", "You matched with" to "O tsamaellana le"
)
