name: CI

on:
  push:
    branches:
      - master
      - Features
  pull_request:
    branches:
      - master
      - Features

jobs:

  android:
    name: Android Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Run Android unit tests
        run: ./gradlew test


  api:
    name: .NET API Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore API
        run: dotnet restore ./SwipeHire.Api/SwipeHire.Api.csproj

      - name: Build API
        run: dotnet build ./SwipeHire.Api/SwipeHire.Api.csproj --no-restore --configuration Release
