name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore API
        run: dotnet restore SwipeHire.Api/SwipeHire.Api.csproj

      - name: Build API
        run: dotnet build SwipeHire.Api/SwipeHire.Api.csproj --no-restore --configuration Release

      - name: Restore tests
        run: dotnet restore SwipeHire.Api.Tests/SwipeHire.Api.Tests.csproj

      - name: Build tests
        run: dotnet build SwipeHire.Api.Tests/SwipeHire.Api.Tests.csproj --no-restore --configuration Release

      - name: Run unit tests
        run: dotnet test SwipeHire.Api.Tests/SwipeHire.Api.Tests.csproj --no-build --configuration Release
